Remove 'pkg publisher' illegal option in DDU
Repository (`F5`) option of DDU ends with:
```
root@ddu:~# ddu-text
Traceback (most recent call last):
  File "/usr/bin/ddu-text", line 79, in <module>
    screen = screen.show()
  File "/usr/ddu/ddu-text/utils/device_scan.py", line 251, in show
    return self.main_win.process_input(self)
  File "/usr/ddu/ddu-text/utils/main_window.py", line 151, in
process_input
    input = self.central_area.process(input)
  File "/usr/ddu/ddu-text/utils/inner_window.py", line 865, in process
    return handler(input)
  File "/usr/ddu/ddu-text/utils/inner_window.py", line 839, in on_key_f5
    self.repo_candi = ddu_build_repo_list(repo_list)
  File "/usr/lib/python2.7/vendor-packages/DDU/ddu_function.py", line
39, in ddu_build_repo_list
    "Arg is not a non-empty ips_repo_list")
DDU.ddu_errors.RepositoryNotFoundException: Arg is not a non-empty
ips_repo_list
```
It's due to:
```
root@ddu:~# cat /tmp/ddu_err.log
pkg publisher: illegal option -- a
Usage:
        pkg publisher [-HPn] [-F format] [publisher ...]
```
Just removing the `-a` option makes the installation of package from
publisher work again.